Git stage

diff --git a/git-feature b/git-feature
--- a/git-feature
+++ b/git-feature
@@ -84,13 +84,36 @@ case $1 in
       git branch -D $feature_branch
       echo "Feature $feature_branch deleted successfully."
     else
-      echo "Aborted by user"
+      echo 'Aborted by user.'
     fi
     exit 0
     ;;
 
-#  stage)
-    
+  stage)
+    if [[ -z $2 ]]; then
+      local branch=$(get_current_branch)
+    else
+      local branch="$FEATURE_PREFIX$2"
+    fi
+    if [[ $MAIN_BRANCH -eq $2 || $MAIN_BRANCH -eq $branch || ! $(is_branch_existent $branch) ]]; then
+      echo "Invalid branch for staging environment."
+      exit 7
+    fi
+    printf "%s \n" "Are you sure you want to make branch $branch eligible for release? [y/n]"
+    if read -q; then
+      if [[ ! $(is_branch_existent $STAGE_BRANCH) ]]; then
+        if [[ $MAIN_BRANCH -ne $(get_current_branch) ]]; then
+          git checkout $MAIN_BRANCH
+        fi
+        git branch $STAGE_BRANCH
+      fi
+      git checkout $STAGE_BRANCH
+      git merge $branch
+    else
+      echo 'Aborted by user.'
+    fi
+    exit 0
+    ;;
 
   *)
     echo 'Please provide which subcommand you want to execute with git-feature:'
@@ -99,5 +122,3 @@ case $1 in
     exit 99
     ;;  
 esac
-
-
